use_frameworks!

platform :ios, '9.0'

target 'KZWFoundation_Example' do
  pod 'KZWFoundation', :path => '../'

  target 'KZWFoundation_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
